require("mani.options")
require("mani.plugins")
-- require("mani.colorscheme")
-- require("mani.nvim-tree")
-- require("mani.completion")
-- require("mani.bufferline")
require("mani.keymaps")
-- require("mani.whichkey")
-- require("mani.treesitter")
-- require("mani.illuminate")
-- require("mani.lsp")
-- require("mani.comment")
-- require("mani.telescope")
-- require("mani.dressing")
-- require("mani.breadcrumbs")
-- require("mani.indentlines")
-- require("mani.lualine")
-- require("mani.impatient")
-- require("mani.toggleterm")
-- require("mani.gitsigns")
-- require("mani.autopairs")
-- require("mani.focus")
-- require("mani.goto-preview")
-- require("mani.alpha")
require("mani.projects")
-- require("mani.copilot")
-- require("mani.copilot-cmp")
-- require("mani.zen_mode")
-- require("mani.codeium")
-- require("mani.flash-nvim")
require("mani.autocmds")
